title:              Rajat Shetty's Blog
email:              your-email@example.com
description:        Good thing!
author:             Rajat Shetty
baseurl:            ""
url:                "rajat-shetty.github.io"

# Social Profiles
twitter_username:   Startthejay
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code
theme: jekyll-theme-clean-blog
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
