title:              CONSTANT CHAOS
email:              rajat.shetty88@gmail.com
description:        
author:             Rajat Shetty
baseurl:            ""
url:                "rajat-shetty.github.io"

# Social Profiles
twitter_username:starthejay
instagram_username:startthejay
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code
theme: jekyll-theme-clean-blog
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
